project:
  type: website
  output-dir: docs
  resources:
    - "*.xlsx"
    - "*.xlsm"
    - "*.xls"
    - "*.pptx"
    - "*.pdf"
    - "*.docx"
    - "*.amua"
    - "*.csv"
    - "*.zip"

website:
  title: "Decision Analysis Workshop - Cebu"
  site-url: "https://geratcliff.github.io/vital-2026-Cebu"
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: capstone/prework.qmd
        text: Before you arrive
      - section: "Model Diagram Drawing Resources"
        contents:
          - text: Draw.io
          - href: http://www.draw.io
      - section: "Amua Resources"
        contents:
          - text: Center for Health Decision Sciences Amua Resources
            href: case-studies/2024_chds_amua_tutorials_tp.pdf
          - text: How to Watch (Amua Video Tutorial)
            href: https://vimeo.com/888816562
          - text: Introductions (Amua Video Tutorial)
            href: https://vimeo.com/888816572
          - text: Basic Layout (Amua Video Tutorial)
            href: https://vimeo.com/888812546
          - text: Decision Trees (Amua Video Tutorial)
            href: https://vimeo.com/888816515
          - text: Markov Models (Amua Video Tutorial)
            href: https://vimeo.com/888816536
      - section: "Advanced Methods"
        contents:
          - text: Modeling Disability-Adjusted Life Years 
            href: https://graveja0.github.io/dalys/
          - text: Intermediate / Advanced Workshop Materials
            href: https://smdm-europe23-what-they-didnt-teach.netlify.app
          - text: Basic Markov Cohort Modeling in R
            href: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9742144/
          - text: Time-Dependent Markov Modeling in R
            href: https://journals.sagepub.com/doi/full/10.1177/0272989X221121747
      - section: "Previous Workshops"
        contents:
          - text: Health Economic Modeling - Bangkok, Thailand (5-day Workshop, 2022) 
            href: https://vchem-vital-workshop-2022.netlify.app/ 
          - text: Adapting Models for LMICs - Cape Town, South Africa (1-day Workshop at IHEA Congress, 2023) 
            href: https://ihea2023-adapting-models-for-lmics.netlify.app/
          - text: Decision Analysis and Economic Evaluation for Clinical Leaders - Kano, Nigeria (5-day workshop, 2023)
            href: https://graveja0.github.io/v-brch-nigeria-2023/ 
          - text: Health Economic Modeling - Bogota, Columbia (4-day Workshop, 2024) 
            href: https://graveja0.github.io/bogota-vital-strategies/
          - text: Health Economic Modeling -Istanbul, TÃ¼rkiye (6-day Workshop, 2024) 
            href: https://graveja0.github.io/vital-istanbul-2024/
          - text: Advanced Health Economic Modeling -Nashville, Tennessee, United States (3-week Fellowship, 2025)
            href: https://graveja0.github.io/vital-fellows-2025-website/index.html
          - text: DALYs in AMUA - Nusa Dua, Bali, Indonesia (1-day Workshop at IHEA Congress, 2025)
            href: https://ihea2025-vanderbilt.netlify.app/
            
      - href: about.qmd
        text: Instructors
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true  # never re-render during project render